version: '3.3'

services:
  paper-cms:
    build:
      context: ../../
      dockerfile: ./docker/std/Dockerfile
    volumes:
      - ./.volume/.data:/usr/app/.data
    ports:
      - 127.0.0.1:7777:7777
