version: '3.3'

services:
  paper-cms:
    env_file: .env
    build:
      context: ../../
      dockerfile: ./docker/std/Dockerfile
    volumes:
      - ./.volume/.data:/usr/app/.data
    networks:
      - internal
      - rproxy-traefik_daemon
    environment:
      PAPER_DEMO_MODE: ${PAPER_DEMO_MODE:-false}
    labels:
      - traefik.docker.network=rproxy-traefik_daemon
      - traefik.http.routers.paper-cms.rule=Host(`${SITE_HOST:?}`)

      - traefik.http.routers.paper-cms.entrypoints=websecure
      # - traefik.http.routers.paper-cms.tls=true
      - traefik.http.routers.paper-cms.tls.certresolver=myresolver
      - traefik.http.services.paper-cms.loadbalancer.server.port=${PAPER_PORT:-7777}

networks:
  internal:
    driver: bridge
  rproxy-traefik_daemon:
    external: true
